### ISSUE TITLE
mardor/mozilla.py <- what's the intent?

### ISSUE THREAD

**Issue by hwine** [mozilla/build-mar#41]
Currently, it has both the primary & secondary keys that are currently active for release.

Is the intent to keep it in sync with changes?

Are you open to also adding some history and metadata? (active dates)

THANK YOU for this package!

**Comment by catlee** [comment]
I would like to keep them in sync with changes. The `get_mozilla_keys.sh` script will suck down the latest supported keys.

I haven't thought about how to handle historic keys and metadata. Do you have any ideas?

**Comment by hwine** [comment]
I probably will. :)  I mostly asked now to know whether or not I had to fork.

For now, I'll assume I'll use a separate file for historic keys. That will keep your build process intact.

The "history" support is more of a "nice to have" feature on my end. Even the exe handling doesn't support ancient history (unsigned stub installers).
